# action.yml
name: 'Build Python manylinux wheel'
author: 'Stefan Jeske, Max Last'
description: 'Build manylinux wheels for a Python package'

inputs:
  usd-image:
    description: 'Which ci-usd image to use, e.g. 2019.9 or 2021.6'
    required: true

runs:
  using: "composite"
  steps:
    - run: echo Hello ${{ inputs.usd-image }}.
      shell: bash
    - run: echo Hello ${{ inputs.usd-image }}.
      shell: bash