name: Wheels

on: [push]

jobs:
  py37:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/build-python3.7
      - uses: actions/upload-artifact@v2
        with:
          name: wheel
          path: dist/*-manylinux*.whl